SET(SOURCES ui_screen_intro.c
    ui_screen_status.c
    ui_screen_setup.c
    ui.c
    ui_comp_hook.c
    ui_helpers.c
    ui_img_front_cover_png.c
    ui_img_cap_png.c
    ui_img_gif1_png.c
    ui_img_printer_png.c
    ui_img_ams_png.c
    ui_img_kitten_stage24_png.c
    ui_img_print_status_png.c
    ui_img_print_head_png.c
    ui_img_empty_png.c
    ui_img_ams_box_png.c
    ui_img_qr_png.c
    ui_img_kitten_stage0_png.c
    ui_img_kitten_stage1_png.c
    ui_img_kitten_stage13_png.c
    ui_img_kitten_stage14_png.c
    ui_img_kitten_stage2_png.c
    ui_img_kitten_stage255_png.c
    ui_img_kitten_stage4_png.c
    ui_img_kitten_stage5_png.c
    ui_img_kitten_stage8_png.c
    ui_img_kitten_stage_1_png.c
    ui_img_kitten_swing_png.c
    ui_img_puppy_stage0_png.c
    ui_img_puppy_stage1_png.c
    ui_img_puppy_stage13_png.c
    ui_img_puppy_stage14_png.c
    ui_img_puppy_stage2_png.c
    ui_img_puppy_stage24_png.c
    ui_img_puppy_stage255_png.c
    ui_img_puppy_stage4_png.c
    ui_img_puppy_stage5_png.c
    ui_img_puppy_stage8_png.c
    ui_img_puppy_stage_1_png.c
    ui_img_puppy_swing_png.c
    ui_img_gif2_png.c
    ui_img_gif3_png.c)

add_library(ui ${SOURCES})
