// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: printpoop

#ifndef _PRINTPOOP_UI_H
#define _PRINTPOOP_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_screen_intro.h"
#include "ui_screen_status.h"
#include "ui_screen_setup.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * spin_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * slowblink_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * sway_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * shake_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * gif_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * swing_Animation( lv_obj_t *TargetObject, int delay);

// EVENTS
extern lv_obj_t *ui_startevents____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_front_cover_png);   // assets/front_cover.png
LV_IMG_DECLARE( ui_img_cap_png);   // assets/cap.png
LV_IMG_DECLARE( ui_img_gif1_png);   // assets/gif1.png
LV_IMG_DECLARE( ui_img_printer_png);   // assets/printer.png
LV_IMG_DECLARE( ui_img_ams_png);   // assets/ams.png
LV_IMG_DECLARE( ui_img_kitten_stage24_png);   // assets/kitten/stage24.png
LV_IMG_DECLARE( ui_img_print_status_png);   // assets/print_status.png
LV_IMG_DECLARE( ui_img_print_head_png);   // assets/print_head.png
LV_IMG_DECLARE( ui_img_empty_png);   // assets/empty.png
LV_IMG_DECLARE( ui_img_ams_box_png);   // assets/ams_box.png
LV_IMG_DECLARE( ui_img_qr_png);   // assets/qr.png
LV_IMG_DECLARE( ui_img_kitten_stage0_png);   // assets/kitten/stage0.png
LV_IMG_DECLARE( ui_img_kitten_stage1_png);   // assets/kitten/stage1.png
LV_IMG_DECLARE( ui_img_kitten_stage13_png);   // assets/kitten/stage13.png
LV_IMG_DECLARE( ui_img_kitten_stage14_png);   // assets/kitten/stage14.png
LV_IMG_DECLARE( ui_img_kitten_stage2_png);   // assets/kitten/stage2.png
LV_IMG_DECLARE( ui_img_kitten_stage255_png);   // assets/kitten/stage255.png
LV_IMG_DECLARE( ui_img_kitten_stage4_png);   // assets/kitten/stage4.png
LV_IMG_DECLARE( ui_img_kitten_stage5_png);   // assets/kitten/stage5.png
LV_IMG_DECLARE( ui_img_kitten_stage8_png);   // assets/kitten/stage8.png
LV_IMG_DECLARE( ui_img_kitten_stage_1_png);   // assets/kitten/stage_1.png
LV_IMG_DECLARE( ui_img_kitten_swing_png);   // assets/kitten/swing.png
LV_IMG_DECLARE( ui_img_puppy_stage0_png);   // assets/puppy/stage0.png
LV_IMG_DECLARE( ui_img_puppy_stage1_png);   // assets/puppy/stage1.png
LV_IMG_DECLARE( ui_img_puppy_stage13_png);   // assets/puppy/stage13.png
LV_IMG_DECLARE( ui_img_puppy_stage14_png);   // assets/puppy/stage14.png
LV_IMG_DECLARE( ui_img_puppy_stage2_png);   // assets/puppy/stage2.png
LV_IMG_DECLARE( ui_img_puppy_stage24_png);   // assets/puppy/stage24.png
LV_IMG_DECLARE( ui_img_puppy_stage255_png);   // assets/puppy/stage255.png
LV_IMG_DECLARE( ui_img_puppy_stage4_png);   // assets/puppy/stage4.png
LV_IMG_DECLARE( ui_img_puppy_stage5_png);   // assets/puppy/stage5.png
LV_IMG_DECLARE( ui_img_puppy_stage8_png);   // assets/puppy/stage8.png
LV_IMG_DECLARE( ui_img_puppy_stage_1_png);   // assets/puppy/stage_1.png
LV_IMG_DECLARE( ui_img_puppy_swing_png);   // assets/puppy/swing.png
LV_IMG_DECLARE( ui_img_gif2_png);   // assets/gif2.png
LV_IMG_DECLARE( ui_img_gif3_png);   // assets/gif3.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
