// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: printpoop

#include "ui.h"

lv_obj_t *ui_screen_setup = NULL;lv_obj_t *ui_setup_tabview_tabview1 = NULL;lv_obj_t *ui_setup_tabpage_wifitab = NULL;lv_obj_t *ui_setup_button_wifiscan = NULL;lv_obj_t *ui_setup_label_label2 = NULL;lv_obj_t *ui_setup_label_networkcount = NULL;lv_obj_t *ui_setup_roller_ssid = NULL;lv_obj_t *ui_setup_label_wifissid = NULL;lv_obj_t *ui_setup_textarea_password = NULL;lv_obj_t *ui_setup_button_savewifi = NULL;lv_obj_t *ui_setup_label_setup_label3 = NULL;lv_obj_t *ui_setup_tabpage_printertab = NULL;lv_obj_t *ui_setup_textarea_printerip = NULL;lv_obj_t *ui_setup_textarea_accesscode = NULL;lv_obj_t *ui_setup_textarea_printerserial = NULL;lv_obj_t *ui_setup_textarea_timezone = NULL;lv_obj_t *ui_setup_button_saveprinter = NULL;lv_obj_t *ui_setup_label_setup_label2 = NULL;lv_obj_t *ui_setup_label_label3 = NULL;lv_obj_t *ui_setup_label_label4 = NULL;lv_obj_t *ui_setup_label_label5 = NULL;lv_obj_t *ui_setup_tabpage_abouttab = NULL;lv_obj_t *ui_setup_textarea_filelist = NULL;lv_obj_t *ui_setup_button_loadimage = NULL;lv_obj_t *ui_setup_label_setup_label4 = NULL;lv_obj_t *ui_setup_button_close = NULL;lv_obj_t *ui_setup_label_setup_label1 = NULL;lv_obj_t *ui_setup_keyboard_keyboard1 = NULL;
// event funtions
void ui_event_setup_tabview_tabview1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      setupTabChanged( e );
}
}

void ui_event_setup_button_wifiscan( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      listNetwork( e );
}
}

void ui_event_setup_textarea_password( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_setup_keyboard_keyboard1,  ui_setup_textarea_password);
      togglekeyboard( e );
}
}

void ui_event_setup_button_savewifi( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      saveWiFiSetup( e );
}
}

void ui_event_setup_textarea_printerip( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_setup_keyboard_keyboard1,  ui_setup_textarea_printerip);
      togglekeyboard( e );
}
}

void ui_event_setup_textarea_accesscode( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_setup_keyboard_keyboard1,  ui_setup_textarea_accesscode);
      togglekeyboard( e );
}
}

void ui_event_setup_textarea_printerserial( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_setup_keyboard_keyboard1,  ui_setup_textarea_printerserial);
      togglekeyboard( e );
}
}

void ui_event_setup_textarea_timezone( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_setup_keyboard_keyboard1,  ui_setup_textarea_timezone);
      togglekeyboard( e );
}
}

void ui_event_setup_button_saveprinter( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      savePrinterSetup( e );
}
}

void ui_event_setup_button_loadimage( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      funfunfun( e );
}
}

void ui_event_setup_button_close( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_screen_status, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_screen_status_screen_init);
      closeSetupScreen( e );
}
}

void ui_event_setup_keyboard_keyboard1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      readKeyboard( e );
}
}

// build funtions

void ui_screen_setup_screen_init(void)
{
ui_screen_setup = lv_obj_create(NULL);
lv_obj_clear_flag( ui_screen_setup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_screen_setup, LV_SCROLLBAR_MODE_OFF);

ui_setup_tabview_tabview1 = lv_tabview_create(ui_screen_setup, LV_DIR_TOP, 25);
lv_obj_set_width( ui_setup_tabview_tabview1, lv_pct(100));
lv_obj_set_height( ui_setup_tabview_tabview1, lv_pct(100));
lv_obj_set_align( ui_setup_tabview_tabview1, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_setup_tabview_tabview1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_setup_tabview_tabview1, lv_color_hex(0x74C7F8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_setup_tabview_tabview1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_setup_tabview_tabview1, lv_color_hex(0x022D4A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_setup_tabview_tabview1, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_setup_tabview_tabview1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_setup_tabview_tabview1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_setup_tabview_tabview1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_setup_tabview_tabview1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_setup_tabview_tabview1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_setup_tabview_tabview1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_setup_tabview_tabview1), lv_color_hex(0x1F07F9),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_setup_tabview_tabview1), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_clip_corner(lv_tabview_get_tab_btns(ui_setup_tabview_tabview1), false,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_setup_tabview_tabview1), lv_color_hex(0x0F0F0F),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_setup_tabview_tabview1), 255,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_setup_tabview_tabview1), &lv_font_montserrat_18,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_setup_tabview_tabview1), lv_color_hex(0xFFFFFF),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_setup_tabview_tabview1), 255,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_setup_tabview_tabview1), lv_color_hex(0x000000),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_setup_tabview_tabview1), 255,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(lv_tabview_get_tab_btns(ui_setup_tabview_tabview1), LV_BORDER_SIDE_LEFT,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(lv_tabview_get_tab_btns(ui_setup_tabview_tabview1), lv_color_hex(0x000000),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(lv_tabview_get_tab_btns(ui_setup_tabview_tabview1), 255,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(lv_tabview_get_tab_btns(ui_setup_tabview_tabview1), 1,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(lv_tabview_get_tab_btns(ui_setup_tabview_tabview1), 0,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_setup_tabview_tabview1), lv_color_hex(0xFBF9F9),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_setup_tabview_tabview1), 255,  LV_PART_ITEMS| LV_STATE_CHECKED);

ui_setup_tabpage_wifitab = lv_tabview_add_tab(ui_setup_tabview_tabview1, "Wi-Fi");
lv_obj_clear_flag( ui_setup_tabpage_wifitab, LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_setup_button_wifiscan = lv_btn_create(ui_setup_tabpage_wifitab);
lv_obj_set_width( ui_setup_button_wifiscan, 70);
lv_obj_set_height( ui_setup_button_wifiscan, 24);
lv_obj_set_x( ui_setup_button_wifiscan, -11 );
lv_obj_set_y( ui_setup_button_wifiscan, -11 );
lv_obj_add_flag( ui_setup_button_wifiscan, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_setup_button_wifiscan, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_setup_button_wifiscan, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_setup_button_wifiscan, lv_color_hex(0xFA01D7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_setup_button_wifiscan, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_setup_button_wifiscan, lv_color_hex(0x4B0155), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_setup_button_wifiscan, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_setup_button_wifiscan, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_setup_button_wifiscan, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_setup_button_wifiscan, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_setup_label_label2 = lv_label_create(ui_setup_button_wifiscan);
lv_obj_set_width( ui_setup_label_label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_setup_label_label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_setup_label_label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_setup_label_label2,"SCAN");
lv_obj_set_style_text_color(ui_setup_label_label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_setup_label_label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_setup_label_networkcount = lv_label_create(ui_setup_tabpage_wifitab);
lv_obj_set_width( ui_setup_label_networkcount, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_setup_label_networkcount, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_setup_label_networkcount, 10 );
lv_obj_set_y( ui_setup_label_networkcount, -7 );
lv_obj_set_align( ui_setup_label_networkcount, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_setup_label_networkcount,"Click & wait Wi-Fi scan");

ui_setup_roller_ssid = lv_roller_create(ui_setup_tabpage_wifitab);
lv_roller_set_options( ui_setup_roller_ssid, "Choose the WiFi Network", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_setup_roller_ssid, 70);
lv_obj_set_width( ui_setup_roller_ssid, lv_pct(100));
lv_obj_set_x( ui_setup_roller_ssid, 0 );
lv_obj_set_y( ui_setup_roller_ssid, 16 );
lv_obj_set_align( ui_setup_roller_ssid, LV_ALIGN_TOP_MID );
lv_obj_set_style_text_letter_space(ui_setup_roller_ssid, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_setup_roller_ssid, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_setup_roller_ssid, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_setup_roller_ssid, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_setup_roller_ssid, lv_color_hex(0x444444), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_setup_roller_ssid, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_setup_label_wifissid = lv_label_create(ui_setup_tabpage_wifitab);
lv_obj_set_width( ui_setup_label_wifissid, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_setup_label_wifissid, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_setup_label_wifissid, 0 );
lv_obj_set_y( ui_setup_label_wifissid, 89 );
lv_obj_set_align( ui_setup_label_wifissid, LV_ALIGN_TOP_MID );
lv_label_set_long_mode(ui_setup_label_wifissid,LV_LABEL_LONG_SCROLL);
lv_label_set_text(ui_setup_label_wifissid,"-");
lv_obj_set_style_text_color(ui_setup_label_wifissid, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_setup_label_wifissid, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_setup_label_wifissid, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_setup_textarea_password = lv_textarea_create(ui_setup_tabpage_wifitab);
lv_obj_set_width( ui_setup_textarea_password, lv_pct(100));
lv_obj_set_height( ui_setup_textarea_password, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_setup_textarea_password, 0 );
lv_obj_set_y( ui_setup_textarea_password, 110 );
lv_obj_set_align( ui_setup_textarea_password, LV_ALIGN_TOP_MID );
lv_textarea_set_max_length(ui_setup_textarea_password,48);
lv_textarea_set_placeholder_text(ui_setup_textarea_password,"Password");
lv_textarea_set_one_line(ui_setup_textarea_password,true);
lv_obj_set_style_border_color(ui_setup_textarea_password, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_setup_textarea_password, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_setup_textarea_password, lv_color_hex(0x808080), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_setup_textarea_password, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_setup_textarea_password, &lv_font_montserrat_12, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_setup_button_savewifi = lv_btn_create(ui_setup_tabpage_wifitab);
lv_obj_set_width( ui_setup_button_savewifi, 120);
lv_obj_set_height( ui_setup_button_savewifi, 40);
lv_obj_set_x( ui_setup_button_savewifi, 0 );
lv_obj_set_y( ui_setup_button_savewifi, -53 );
lv_obj_set_align( ui_setup_button_savewifi, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_setup_button_savewifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_setup_button_savewifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_setup_button_savewifi, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_setup_button_savewifi, lv_color_hex(0x4A61FE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_setup_button_savewifi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_setup_button_savewifi, lv_color_hex(0x2A307C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_setup_button_savewifi, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_setup_button_savewifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_setup_button_savewifi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_setup_button_savewifi, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_setup_button_savewifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_setup_button_savewifi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_setup_label_setup_label3 = lv_label_create(ui_setup_button_savewifi);
lv_obj_set_width( ui_setup_label_setup_label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_setup_label_setup_label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_setup_label_setup_label3, 0 );
lv_obj_set_y( ui_setup_label_setup_label3, -1 );
lv_obj_set_align( ui_setup_label_setup_label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_setup_label_setup_label3,"SAVE");
lv_obj_set_style_text_font(ui_setup_label_setup_label3, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_setup_tabpage_printertab = lv_tabview_add_tab(ui_setup_tabview_tabview1, "Printer");
lv_obj_clear_flag( ui_setup_tabpage_printertab, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_setup_textarea_printerip = lv_textarea_create(ui_setup_tabpage_printertab);
lv_obj_set_width( ui_setup_textarea_printerip, 110);
lv_obj_set_height( ui_setup_textarea_printerip, LV_SIZE_CONTENT);   /// 20
lv_obj_set_x( ui_setup_textarea_printerip, -10 );
lv_obj_set_y( ui_setup_textarea_printerip, 14 );
lv_textarea_set_accepted_chars(ui_setup_textarea_printerip, "0123456789.");
lv_textarea_set_max_length(ui_setup_textarea_printerip,15);
lv_textarea_set_placeholder_text(ui_setup_textarea_printerip,"0.0.0.0");
lv_textarea_set_one_line(ui_setup_textarea_printerip,true);
lv_obj_set_style_border_color(ui_setup_textarea_printerip, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_setup_textarea_printerip, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_setup_textarea_printerip, lv_color_hex(0x808080), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_setup_textarea_printerip, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_setup_textarea_printerip, &lv_font_montserrat_12, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_setup_textarea_accesscode = lv_textarea_create(ui_setup_tabpage_printertab);
lv_obj_set_width( ui_setup_textarea_accesscode, 110);
lv_obj_set_height( ui_setup_textarea_accesscode, LV_SIZE_CONTENT);   /// 20
lv_obj_set_x( ui_setup_textarea_accesscode, 10 );
lv_obj_set_y( ui_setup_textarea_accesscode, 14 );
lv_obj_set_align( ui_setup_textarea_accesscode, LV_ALIGN_TOP_RIGHT );
lv_textarea_set_accepted_chars(ui_setup_textarea_accesscode, "0123456789");
lv_textarea_set_max_length(ui_setup_textarea_accesscode,8);
lv_textarea_set_placeholder_text(ui_setup_textarea_accesscode,"00000000");
lv_textarea_set_one_line(ui_setup_textarea_accesscode,true);
lv_obj_set_style_border_color(ui_setup_textarea_accesscode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_setup_textarea_accesscode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_setup_textarea_accesscode, lv_color_hex(0x808080), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_setup_textarea_accesscode, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_setup_textarea_accesscode, &lv_font_montserrat_12, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_setup_textarea_printerserial = lv_textarea_create(ui_setup_tabpage_printertab);
lv_obj_set_width( ui_setup_textarea_printerserial, 180);
lv_obj_set_height( ui_setup_textarea_printerserial, LV_SIZE_CONTENT);   /// 20
lv_obj_set_x( ui_setup_textarea_printerserial, 10 );
lv_obj_set_y( ui_setup_textarea_printerserial, 61 );
lv_obj_set_align( ui_setup_textarea_printerserial, LV_ALIGN_TOP_RIGHT );
lv_textarea_set_accepted_chars(ui_setup_textarea_printerserial, "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ");
lv_textarea_set_max_length(ui_setup_textarea_printerserial,32);
lv_textarea_set_placeholder_text(ui_setup_textarea_printerserial,"case sensitive");
lv_textarea_set_one_line(ui_setup_textarea_printerserial,true);
lv_obj_clear_flag( ui_setup_textarea_printerserial, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_border_color(ui_setup_textarea_printerserial, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_setup_textarea_printerserial, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_setup_textarea_printerserial, lv_color_hex(0x808080), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_setup_textarea_printerserial, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_setup_textarea_printerserial, &lv_font_montserrat_12, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_setup_textarea_timezone = lv_textarea_create(ui_setup_tabpage_printertab);
lv_obj_set_width( ui_setup_textarea_timezone, lv_pct(60));
lv_obj_set_height( ui_setup_textarea_timezone, LV_SIZE_CONTENT);   /// 20
lv_obj_set_x( ui_setup_textarea_timezone, 10 );
lv_obj_set_y( ui_setup_textarea_timezone, 108 );
lv_obj_set_align( ui_setup_textarea_timezone, LV_ALIGN_TOP_RIGHT );
lv_textarea_set_accepted_chars(ui_setup_textarea_timezone, "0123456789-");
lv_textarea_set_max_length(ui_setup_textarea_timezone,3);
lv_textarea_set_placeholder_text(ui_setup_textarea_timezone,"UTC -12 to +14");
lv_textarea_set_one_line(ui_setup_textarea_timezone,true);
lv_obj_clear_flag( ui_setup_textarea_timezone, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_border_color(ui_setup_textarea_timezone, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_setup_textarea_timezone, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_setup_textarea_timezone, lv_color_hex(0x808080), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_setup_textarea_timezone, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_setup_textarea_timezone, &lv_font_montserrat_12, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_setup_button_saveprinter = lv_btn_create(ui_setup_tabpage_printertab);
lv_obj_set_width( ui_setup_button_saveprinter, 120);
lv_obj_set_height( ui_setup_button_saveprinter, 40);
lv_obj_set_x( ui_setup_button_saveprinter, 0 );
lv_obj_set_y( ui_setup_button_saveprinter, -53 );
lv_obj_set_align( ui_setup_button_saveprinter, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_setup_button_saveprinter, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_setup_button_saveprinter, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_setup_button_saveprinter, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_setup_button_saveprinter, lv_color_hex(0xC3FC03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_setup_button_saveprinter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_setup_button_saveprinter, lv_color_hex(0x466300), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_setup_button_saveprinter, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_setup_button_saveprinter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_setup_button_saveprinter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_setup_button_saveprinter, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_setup_button_saveprinter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_setup_button_saveprinter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_setup_label_setup_label2 = lv_label_create(ui_setup_button_saveprinter);
lv_obj_set_width( ui_setup_label_setup_label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_setup_label_setup_label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_setup_label_setup_label2, 0 );
lv_obj_set_y( ui_setup_label_setup_label2, -1 );
lv_obj_set_align( ui_setup_label_setup_label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_setup_label_setup_label2,"SAVE");
lv_obj_set_style_text_font(ui_setup_label_setup_label2, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_setup_label_label3 = lv_label_create(ui_setup_tabpage_printertab);
lv_obj_set_width( ui_setup_label_label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_setup_label_label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_setup_label_label3, 0 );
lv_obj_set_y( ui_setup_label_label3, -6 );
lv_label_set_text(ui_setup_label_label3,"IP Address            Access Code");

ui_setup_label_label4 = lv_label_create(ui_setup_tabpage_printertab);
lv_obj_set_width( ui_setup_label_label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_setup_label_label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_setup_label_label4, -7 );
lv_obj_set_y( ui_setup_label_label4, -6 );
lv_obj_set_align( ui_setup_label_label4, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_setup_label_label4,"Time Zone");

ui_setup_label_label5 = lv_label_create(ui_setup_tabpage_printertab);
lv_obj_set_width( ui_setup_label_label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_setup_label_label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_setup_label_label5, -6 );
lv_obj_set_y( ui_setup_label_label5, -54 );
lv_obj_set_align( ui_setup_label_label5, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_setup_label_label5,"Serial");

ui_setup_tabpage_abouttab = lv_tabview_add_tab(ui_setup_tabview_tabview1, "About");
lv_obj_clear_flag( ui_setup_tabpage_abouttab, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scroll_dir(ui_setup_tabpage_abouttab, LV_DIR_VER);

ui_setup_textarea_filelist = lv_textarea_create(ui_setup_tabpage_abouttab);
lv_obj_set_height( ui_setup_textarea_filelist, 150);
lv_obj_set_width( ui_setup_textarea_filelist, lv_pct(100));
lv_obj_set_align( ui_setup_textarea_filelist, LV_ALIGN_TOP_MID );
lv_obj_set_style_border_color(ui_setup_textarea_filelist, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_setup_textarea_filelist, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_setup_textarea_filelist, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_setup_textarea_filelist, lv_color_hex(0x333333), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_setup_textarea_filelist, 255, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

ui_setup_button_loadimage = lv_btn_create(ui_setup_tabpage_abouttab);
lv_obj_set_width( ui_setup_button_loadimage, 120);
lv_obj_set_height( ui_setup_button_loadimage, 40);
lv_obj_set_x( ui_setup_button_loadimage, 0 );
lv_obj_set_y( ui_setup_button_loadimage, -53 );
lv_obj_set_align( ui_setup_button_loadimage, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_setup_button_loadimage, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_setup_button_loadimage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_setup_button_loadimage, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_setup_button_loadimage, lv_color_hex(0x7AFD96), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_setup_button_loadimage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_setup_button_loadimage, lv_color_hex(0x3C7B49), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_setup_button_loadimage, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_setup_button_loadimage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_setup_button_loadimage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_setup_button_loadimage, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_setup_button_loadimage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_setup_button_loadimage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_setup_label_setup_label4 = lv_label_create(ui_setup_button_loadimage);
lv_obj_set_width( ui_setup_label_setup_label4, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_setup_label_setup_label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_setup_label_setup_label4, 0 );
lv_obj_set_y( ui_setup_label_setup_label4, -1 );
lv_obj_set_align( ui_setup_label_setup_label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_setup_label_setup_label4,"Load");
lv_obj_set_style_text_font(ui_setup_label_setup_label4, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_setup_button_close = lv_btn_create(ui_screen_setup);
lv_obj_set_width( ui_setup_button_close, 120);
lv_obj_set_height( ui_setup_button_close, 40);
lv_obj_set_align( ui_setup_button_close, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_setup_button_close, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_setup_button_close, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_setup_button_close, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_setup_button_close, lv_color_hex(0xFCFCFD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_setup_button_close, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_setup_button_close, lv_color_hex(0x8E8C8C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_setup_button_close, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_setup_button_close, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_setup_button_close, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_setup_button_close, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_setup_button_close, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_setup_button_close, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_setup_label_setup_label1 = lv_label_create(ui_setup_button_close);
lv_obj_set_width( ui_setup_label_setup_label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_setup_label_setup_label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_setup_label_setup_label1, 0 );
lv_obj_set_y( ui_setup_label_setup_label1, -1 );
lv_obj_set_align( ui_setup_label_setup_label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_setup_label_setup_label1,"CLOSE");
lv_obj_set_style_text_font(ui_setup_label_setup_label1, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_setup_keyboard_keyboard1 = lv_keyboard_create(ui_screen_setup);
lv_obj_set_height( ui_setup_keyboard_keyboard1, 130);
lv_obj_set_width( ui_setup_keyboard_keyboard1, lv_pct(100));
lv_obj_set_align( ui_setup_keyboard_keyboard1, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_setup_keyboard_keyboard1, LV_OBJ_FLAG_HIDDEN );   /// Flags

lv_obj_add_event_cb(ui_setup_button_wifiscan, ui_event_setup_button_wifiscan, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_setup_textarea_password, ui_event_setup_textarea_password, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_setup_button_savewifi, ui_event_setup_button_savewifi, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_setup_textarea_printerip, ui_event_setup_textarea_printerip, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_setup_textarea_accesscode, ui_event_setup_textarea_accesscode, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_setup_textarea_printerserial, ui_event_setup_textarea_printerserial, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_setup_textarea_timezone, ui_event_setup_textarea_timezone, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_setup_button_saveprinter, ui_event_setup_button_saveprinter, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_setup_button_loadimage, ui_event_setup_button_loadimage, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_setup_tabview_tabview1, ui_event_setup_tabview_tabview1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_setup_button_close, ui_event_setup_button_close, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_setup_keyboard_keyboard1, ui_event_setup_keyboard_keyboard1, LV_EVENT_ALL, NULL);

}

void ui_screen_setup_screen_destroy(void)
{
   if (ui_screen_setup) lv_obj_del(ui_screen_setup);

// NULL screen variables
ui_screen_setup= NULL;
ui_setup_tabview_tabview1= NULL;
ui_setup_tabpage_wifitab= NULL;
ui_setup_button_wifiscan= NULL;
ui_setup_label_label2= NULL;
ui_setup_label_networkcount= NULL;
ui_setup_roller_ssid= NULL;
ui_setup_label_wifissid= NULL;
ui_setup_textarea_password= NULL;
ui_setup_button_savewifi= NULL;
ui_setup_label_setup_label3= NULL;
ui_setup_tabpage_printertab= NULL;
ui_setup_textarea_printerip= NULL;
ui_setup_textarea_accesscode= NULL;
ui_setup_textarea_printerserial= NULL;
ui_setup_textarea_timezone= NULL;
ui_setup_button_saveprinter= NULL;
ui_setup_label_setup_label2= NULL;
ui_setup_label_label3= NULL;
ui_setup_label_label4= NULL;
ui_setup_label_label5= NULL;
ui_setup_tabpage_abouttab= NULL;
ui_setup_textarea_filelist= NULL;
ui_setup_button_loadimage= NULL;
ui_setup_label_setup_label4= NULL;
ui_setup_button_close= NULL;
ui_setup_label_setup_label1= NULL;
ui_setup_keyboard_keyboard1= NULL;

}
