// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: printpoop

#ifndef UI_SCREEN_SETUP_H
#define UI_SCREEN_SETUP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_setup
extern void ui_screen_setup_screen_init(void);
extern void ui_screen_setup_screen_destroy(void);
extern lv_obj_t *ui_screen_setup;
extern void ui_event_setup_tabview_tabview1( lv_event_t * e);
extern lv_obj_t *ui_setup_tabview_tabview1;
extern lv_obj_t *ui_setup_tabpage_wifitab;
extern void ui_event_setup_button_wifiscan( lv_event_t * e);
extern lv_obj_t *ui_setup_button_wifiscan;
extern lv_obj_t *ui_setup_label_label2;
extern lv_obj_t *ui_setup_label_networkcount;
extern lv_obj_t *ui_setup_roller_ssid;
extern lv_obj_t *ui_setup_label_wifissid;
extern void ui_event_setup_textarea_password( lv_event_t * e);
extern lv_obj_t *ui_setup_textarea_password;
extern void ui_event_setup_button_savewifi( lv_event_t * e);
extern lv_obj_t *ui_setup_button_savewifi;
extern lv_obj_t *ui_setup_label_setup_label3;
extern lv_obj_t *ui_setup_tabpage_printertab;
extern void ui_event_setup_textarea_printerip( lv_event_t * e);
extern lv_obj_t *ui_setup_textarea_printerip;
extern void ui_event_setup_textarea_accesscode( lv_event_t * e);
extern lv_obj_t *ui_setup_textarea_accesscode;
extern void ui_event_setup_textarea_printerserial( lv_event_t * e);
extern lv_obj_t *ui_setup_textarea_printerserial;
extern void ui_event_setup_textarea_timezone( lv_event_t * e);
extern lv_obj_t *ui_setup_textarea_timezone;
extern void ui_event_setup_button_saveprinter( lv_event_t * e);
extern lv_obj_t *ui_setup_button_saveprinter;
extern lv_obj_t *ui_setup_label_setup_label2;
extern lv_obj_t *ui_setup_label_label3;
extern lv_obj_t *ui_setup_label_label4;
extern lv_obj_t *ui_setup_label_label5;
extern lv_obj_t *ui_setup_tabpage_screentab;
extern void ui_event_setup_button_loadimage( lv_event_t * e);
extern lv_obj_t *ui_setup_button_loadimage;
extern lv_obj_t *ui_setup_label_setup_label4;
extern lv_obj_t *ui_setup_image_qrcode;
extern void ui_event_setup_button_close( lv_event_t * e);
extern lv_obj_t *ui_setup_button_close;
extern lv_obj_t *ui_setup_label_setup_label1;
extern void ui_event_setup_keyboard_keyboard1( lv_event_t * e);
extern lv_obj_t *ui_setup_keyboard_keyboard1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

